package br.com.utily.ecommerce.util.constant.entity;

public enum EViewType {
    AUTH_APPLICATION,
    ERROR_APPLICATION,

    CUSTOMER_ACCOUNT_SHOP,
    CUSTOMER_ADDRESS_SHOP,
    CUSTOMER_CREDIT_CARD_SHOP,
    CUSTOMER_VOUCHER_SHOP,
    CUSTOMER_ORDER_SHOP,
    CUSTOMER_TRADE_SHOP,
    PRODUCT_SHOP,
    CART_SHOP,
    CHECKOUT_SHOP,
    CHECKOUT_STEP_SHOP,
    CHECKOUT_FINISH_SHOP,

    REDIRECT_TRADE_IN_PROGRESS,

    REDIRECT_PRODUCT_SHOP,
    REDIRECT_CUSTOMER_ACCOUNT_SHOP,
    REDIRECT_LOGIN_APPLICATION,

    REDIRECT_CHECKOUT_STEP_ONE,
    REDIRECT_CHECKOUT_STEP_TWO,
    REDIRECT_CHECKOUT_STEP_THREE,

    REDIRECT_STOCKS_ADMIN,
    REDIRECT_NEW_STOCK_ADMIN,
    REDIRECT_MANAGE_STOCK_ADMIN,

    REDIRECT_PRODUCTS_ADMIN,
    REDIRECT_CUSTOMERS_ADMIN,
    REDIRECT_SALES_ADMIN,
    REDIRECT_TRADES_ADMIN,
    REDIRECT_TRADE_SHOP_FINISH,

    DASHBOARD_ADMIN,
    CATEGORY_ADMIN,
    PROVIDER_ADMIN,
    STOCK_ADMIN,
    STOCK_HISTORY_ADMIN,
    CUSTOMER_ADMIN,
    VOUCHER_ADMIN,
    PRODUCT_ADMIN,
    SALE_ADMIN,
    TRADE_ADMIN;
}
